/*
 * Html attribute type definitions
 * 08/23/2024
 */

#ifndef HTML_ATTRIBUTES_MODULE
#define HTML_ATTRIBUTES_MODULE

enum HTML_ATTR_TYPE {
    HTML_ATTR_ACCEPT,
    HTML_ATTR_AUTOCOMPLETE,

    HTML_ATTR_CAPTURE,
    HTML_ATTR_CROSSORIGIN,

    HTML_ATTR_DIRNAME,
    HTML_ATTR_DISABLED,

    HTML_ATTR_ELEMENTTIMING,

    HTML_ATTR_FOR,
    
    HTML_ATTR_MAX,
    HTML_ATTR_MAXLENGTH,
    HTML_ATTR_MIN,
    HTML_ATTR_MINLENGTH,
    HTML_ATTR_MULTIPLE,

    HTML_ATTR_PATTERN,
    HTML_ATTR_PLACEHOLDER,

    HTML_ATTR_READONLY,
    HTML_ATTR_REL,
    HTML_ATTR_REQUIRED,

    HTML_ATTR_SIZE,
    HTML_ATTR_STEP,

    HTML_ATTR_COUNT_
};

#endif
