/*
 * Html element type declarations
 * 08/23/2024
 */

#ifndef HTML_TOKEN_MODULE
#define HTML_TOKEN_MODULE

enum HTML_ELEM_TYPE {
    HTML_ELEM_A,
    HTML_ELEM_ABBR,
    HTML_ELEM_ADDRESS,
    HTML_ELEM_AREA,
    HTML_ELEM_ARTICLE,
    HTML_ELEM_ASIDE,
    HTML_ELEM_AUDIO,

    HTML_ELEM_B,
    HTML_ELEM_BASE,
    HTML_ELEM_BDI,
    HTML_ELEM_BDO,
    HTML_ELEM_BIG,
    HTML_ELEM_BLOCKQUOTE,
    HTML_ELEM_BODY,
    HTML_ELEM_BR,
    HTML_ELEM_BUTTON,

    HTML_ELEM_CANVAS,
    HTML_ELEM_CAPTION,
    HTML_ELEM_CENTER,
    HTML_ELEM_CITE,
    HTML_ELEM_CODE,
    HTML_ELEM_COL,
    HTML_ELEM_COLGROUP,

    HTML_ELEM_DATA,
    HTML_ELEM_DATALIST,
    HTML_ELEM_DD,
    HTML_ELEM_DEL,
    HTML_ELEM_DETAILS,
    HTML_ELEM_DFN,
    HTML_ELEM_DIALOG,
    HTML_ELEM_DIR,
    HTML_ELEM_DIV,
    HTML_ELEM_DL,
    HTML_ELEM_DT,

    HTML_ELEM_EM,
    HTML_ELEM_EMBED,

    HTML_ELEM_FENCEDFRAME,
    HTML_ELEM_FIELDSET,
    HTML_ELEM_FIGCAPTION,
    HTML_ELEM_FIGURE,
    HTML_ELEM_FONT,
    HTML_ELEM_FOOTER,
    HTML_ELEM_FORM,
    HTML_ELEM_FRAME,
    HTML_ELEM_FRAMESET,

    HTML_ELEM_H1,
    HTML_ELEM_HEAD,
    HTML_ELEM_HEADER,
    HTML_ELEM_HGROUP,
    HTML_ELEM_HR,
    HTML_ELEM_HTML,

    HTML_ELEM_I,
    HTML_ELEM_IFRAME,
    HTML_ELEM_IMG,
    HTML_ELEM_INPUT,
    HTML_ELEM_INS,

    HTML_ELEM_KBD,

    HTML_ELEM_LABEL,
    HTML_ELEM_LEGEND
    HTML_ELEM_LI,
    HTML_ELEM_LINK,

    HTML_ELEM_MAIN,
    HTML_ELEM_MAP,
    HTML_ELEM_MARK,
    HTML_ELEM_MARQUEE,
    HTML_ELEM_MENU,
    HTML_ELEM_META,
    HTML_ELEM_METER,

    HTML_ELEM_NAV,
    HTML_ELEM_NOBR,
    HTML_ELEM_NOEMBED,
    HTML_ELEM_NOFRAMES,
    HTML_ELEM_NOSCRIPT,

    HTML_ELEM_OBJECT,
    HTML_ELEM_OL,
    HTML_ELEM_OPTGROUP,
    HTML_ELEM_OPTION,

    HTML_ELEM_P,
    HTML_ELEM_PARAM,
    HTML_ELEM_PICTURE,
    HTML_ELEM_PLAINTEXT,
    HTML_ELEM_PORTAL,
    HTML_ELEM_PRE,
    HTML_ELEM_PROGRESS,

    HTML_ELEM_Q,

    HTML_ELEM_RB,
    HTML_ELEM_RP,
    HTML_ELEM_RT,
    HTML_ELEM_RTC,
    HTML_ELEM_RUBY,

    HTML_ELEM_S,
    HTML_ELEM_SAMP,
    HTML_ELEM_SCRIPT,
    HTML_ELEM_SEARCH,
    HTML_ELEM_SECTION,
    HTML_ELEM_SELECT,
    HTML_ELEM_SLOT,
    HTML_ELEM_SMALL,
    HTML_ELEM_SOURCE,
    HTML_ELEM_SPAN,
    HTML_ELEM_STRIKE,
    HTML_ELEM_STRONG,
    HTML_ELEM_STYLE,
    HTML_ELEM_SUB,
    HTML_ELEM_SUMMARY,
    HTML_ELEM_SUP,
    HTML_ELEM_TABLE,
    HTML_ELEM_TBODY,
    HTML_ELEM_TD,
    HTML_ELEM_TEMPLATE,
    HTML_ELEM_TEXTAREA,
    HTML_ELEM_TFOOT,
    HTML_ELEM_TH,
    HTML_ELEM_THEAD,
    HTML_ELEM_TIME,
    HTML_ELEM_TITLE,
    HTML_ELEM_TR,
    HTML_ELEM_TRACK,
    HTML_ELEM_TT,

    HTML_ELEM_U,
    HTML_ELEM_UL,

    HTML_ELEM_VAR,
    HTML_ELEM_VIDEO,

    HTML_ELEM_WBR,

    HTML_ELEM_XMP,

    HTML_ELEM_COUNT_
};

#endif
