/*
 * Html input type definitions
 * 08/23/2024
 */

#ifndef HTML_INPUT_TYPE_MODULE
#define HTML_INPUT_TYPE_MODULE

enum HTML_INPUT_TYPE {
    HTML_INPUT_TYPE_BUTTON,
    HTML_INPUT_TYPE_CHECKBOX,
    HTML_INPUT_TYPE_COLOR,
    HTML_INPUT_TYPE_DATE,
    HTML_INPUT_TYPE_DATETIME_LOCAL,
    HTML_INPUT_TYPE_EMAIL,
    HTML_INPUT_TYPE_FILE,
    HTML_INPUT_TYPE_HIDDEN,
    HTML_INPUT_TYPE_IMAGE,
    HTML_INPUT_TYPE_MONTH,
    HTML_INPUT_TYPE_NUMBER,
    HTML_INPUT_TYPE_PASSWORD,
    HTML_INPUT_TYPE_RADIO,
    HTML_INPUT_TYPE_RANGE,
    HTML_INPUT_TYPE_RESET,
    HTML_INPUT_TYPE_SEARCH,
    HTML_INPUT_TYPE_SUBMIT,
    HTML_INPUT_TYPE_TEL,
    HTML_INPUT_TYPE_TEXT,
    HTML_INPUT_TYPE_TIME,
    HTML_INPUT_TYPE_URL,
    HTML_INPUT_TYPE_WEEK,

    HTML_INPUT_TYPE_COUNT_
};

#endif
